sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=26 # emacs-26 branch, built daily
  - EMACS_VERSION=25 # emacs-25 branch, built daily
  - EMACS_VERSION=master # master branch, built daily

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=master

addons:
  apt:
    packages:
      # Install makeinfo [sic] - needed for magit
      - texinfo

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - export EMACS_COMMAND=$EMACS # use helm
  - $EMACS --version
script:
  - git config --global user.name "Kentaro Ohkouchi"
  - git config --global user.email nanasess@example.com
  - $EMACS -q -l init.el --batch
  - $EMACS -q -l init.el --batch -f batch-byte-compile init.el
  - ls el-get/emacs-async
  - cd el-get/helm && make ASYNC_ELPA_DIR=${TRAVIS_BUILD_DIR}/el-get/emacs-async/

notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always # The default.